version: '3.8'

services:
  web:
    build: .
    container_name: telegraph_web # majburiy emas # container nomi
    image: telegraph_web # majburiy emas # image nomi
    ports:
      - "7878:7878"
    restart: unless-stopped # qurilma o'chganda avto restart qilish o'zim to'xtatmaguncha
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=turdalihasanboyev144@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=123
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput || true &&
             python manage.py runserver 0.0.0.0:7878"
